In [25]:
import numpy as np
import scipy as sp
import pandas as pd

In [26]:
hotel = pd.read_csv('D:/hotel_bookings.csv')
hotel

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [27]:
drop_columns=['agent','company','hotel','reservation_status_date']
hotel.drop(inplace=True, axis=1, labels=drop_columns)
hotel.isnull().sum()

is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
dtype: int64

In [23]:
hotel.isnull().sum()
hotel.fillna(hotel.mode().iloc[0], inplace=True)
hotel.isnull().sum()

is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
dtype: int64

In [111]:
X = hotel.iloc[:,1:]
y = hotel.iloc[:,0]

In [112]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   lead_time                       119390 non-null  int64
 1   arrival_date_year               119390 non-null  int64
 2   arrival_date_month              119390 non-null  object
 3   arrival_date_week_number        119390 non-null  int64
 4   arrival_date_day_of_month       119390 non-null  int64
 5   stays_in_weekend_nights         119390 non-null  int64
 6   stays_in_week_nights            119390 non-null  int64
 7   adults                          119390 non-null  int64
 8   children                        119390 non-null  float64
 9   babies                          119390 non-null  int64
 10  meal                            119390 non-null  object
 11  country                         119390 non-null  object
 12  market_segment                  119390 non-null  object
 13  distribution_channel            119390 non-null  object
 14  is_repeated_guest               119390 non-null  int64
 15  previous_cancellations          119390 non-null  int64
 16  previous_bookings_not_canceled  119390 non-null  int64
 17  reserved_room_type              119390 non-null  object
 18  assigned_room_type              119390 non-null  object
 19  booking_changes                 119390 non-null  int64
 20  deposit_type                    119390 non-null  object
 21  days_in_waiting_list            119390 non-null  int64
 22  customer_type                   119390 non-null  object
 23  adr                             119390 non-null  float64
 24  required_car_parking_spaces     119390 non-null  int64
 25  total_of_special_requests       119390 non-null  int64
 26  reservation_status              119390 non-null  object
dtypes: float64(2), int64(15), object(10)
memory usage: 24.6+ MB

In [113]:

from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [114]:
need_transfer=['meal','distribution_channel','reservation_status','country','arrival_date_month','market_segment',
 'deposit_type','customer_type', 'reserved_room_type','assigned_room_type' ]
transfer = make_column_transformer(
    (OneHotEncoder(),need_transfer), remainder = 'passthrough'
    )
X = transfer.fit_transform(X).toarray()

In [115]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape

(95512, 256)

In [116]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
stander = StandardScaler()
X_train = stander.fit_transform(X_train)
X_test = stander.transform(X_test)

In [117]:
pca = PCA(n_components = 100)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print("降维后的训练数据:",X_train.shape,"\n测试数据:",X_test.shape)
print("降维后的训练数据:",X_train,"\n测试数据:",X_test)

降维后的训练数据: (95512, 100)
测试数据: (23878, 100)
降维后的训练数据: [[ -2.60018949   2.7839691    1.58747092 ...  -9.39525264 -12.53514356
  -10.44010567]
 [ -2.07935987   2.26353252   1.22385424 ...   1.15241403   0.84459992
   -0.09848636]
 [ -1.40659735   0.10866818  -1.37975313 ...  -0.26525442  -0.32102147
   -0.51985855]
 ...
 [ -2.6720792    0.15131829   0.06372334 ...   0.02672533  -0.30577138
   -0.85696105]
 [  1.46595174  -0.64006998  -2.53602658 ...  -0.68929303  -0.84055205
   -0.82338925]
 [  3.87673133   1.20430281   2.81120045 ...   0.35781931  -0.22561343
   -0.07924318]]
测试数据: [[ 0.84567945  0.6691737  -1.39471945 ...  0.11851485  0.2003457
   0.04825803]
 [-0.33357348  0.87953587 -1.33834552 ...  0.37640947 -0.28473561
   0.36693467]
 [ 5.29032248  0.68305778  1.47398007 ...  0.17143219 -0.12394839
   0.16016577]
 ...
 [ 1.02162469 -4.4483186  -1.75433843 ...  1.03660803 -0.37439697
  -0.14075871]
 [ 0.85694529 -5.92763469  0.00974258 ...  0.21252337  0.13437824
   0.05887529]
 [-0.82313193  0.78044939 -1.16295047 ... -0.15138057  0.51038575
  -0.07845159]]

In [119]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=10000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [120]:
y_pred = classifier.predict(X_test)

In [122]:
from sklearn.metrics import confusion_matrix
prediction = confusion_matrix(y_test, y_pred)
prediction

array([[14917,    17],
       [   15,  8929]], dtype=int64)

In [123]:
accuracy = (prediction[0][0] + prediction[1][1]) * 100.0 / prediction.sum()
print("The final test accuracy is %.4f%%" % (accuracy))

The final test accuracy is 99.8660%

In [124]:
train_pred = classifier.predict(X_train)
train_prediction = confusion_matrix(y_train,train_pred)
print(train_prediction)
train_accuracy = (train_prediction[0][0] + train_prediction[1][1]) * 100.0 / train_prediction.sum()
print("The final accuracy on training data is %.4f%%" % (train_accuracy))

[[60184    48]
 [   71 35209]]
The final accuracy on training data is 99.8754%